filetype plugin indent on

" Tabs
set tabstop=2
set smarttab
set shiftwidth=2
set autoindent
set expandtab

" Look and Feel
set t_Co=256

syntax on
set background=dark
colorscheme ir_black
set cursorline
set number
set equalalways
set splitbelow splitright
set scrolloff=8
set backspace=indent,eol,start
set shortmess+=I
set clipboard=unnamed
set nopaste

" Key Mappings
imap jj <Esc>
inoremap <tab> <c-n>
nmap <silent> <Leader>n :NERDTreeToggle<CR>
nmap <silent> <Leader>N :NERDTreeFind<CR>
map <leader>F :Ack<space>
nnoremap <leader><leader> <c-^>

" Search
set incsearch
set ignorecase
set smartcase

" Status Line
set laststatus=2
set statusline+=[%F]
set statusline+=[FORMAT=%{&ff}]
set statusline+=[TYPE=%Y]
set statusline+=[POS=%04l,%04v]
set statusline+=[%p%%]
set statusline+=%*
set ruler

" folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

" Swap and Backup Files
set nobackup
set nowritebackup
set noswapfile

" Jump to last cursor position when opening a file.
" Do not do it when writing a commit log entry.
autocmd BufReadPost * call SetCursorPosition()
function! SetCursorPosition()
  if &filetype !~ 'commit\c'
    if line("'\"") > 0 && line("'\"") <= line("$")
     exe "normal g`\""
    endif
  end
endfunction

" F5 to remove trailing white space
nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

